# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whisper_api_sdk.models.similar_domain_request import SimilarDomainRequest

class TestSimilarDomainRequest(unittest.TestCase):
    """SimilarDomainRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SimilarDomainRequest:
        """Test SimilarDomainRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SimilarDomainRequest`
        """
        model = SimilarDomainRequest()
        if include_optional:
            return SimilarDomainRequest(
                techniques = ["typosquatting","homoglyph","bitsquatting"],
                limit = 100,
                check_registration = True,
                include_dns = True,
                include_risk_score = True,
                technique_config = whisper_api_sdk.models.technique_config.TechniqueConfig(
                    typosquatting = whisper_api_sdk.models.typosquatting_config.TyposquattingConfig(
                        character_omission = True, 
                        character_swap = True, 
                        double_character = True, 
                        keyboard_proximity = True, ), 
                    homoglyph = whisper_api_sdk.models.homoglyph_config.HomoglyphConfig(
                        cyrillic = True, 
                        greek = True, 
                        latin = True, 
                        max_substitutions = 2, ), 
                    bitsquatting = whisper_api_sdk.models.bitsquatting_config.BitsquattingConfig(
                        max_bit_flips = 1, ), 
                    tld_variation = whisper_api_sdk.models.tld_variation_config.TldVariationConfig(
                        common_tlds = True, 
                        country_tlds = True, 
                        new_gtlds = True, 
                        custom_tlds = ["io","ai","tech"], ), )
            )
        else:
            return SimilarDomainRequest(
        )
        """

    def testSimilarDomainRequest(self):
        """Test SimilarDomainRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
