# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whisper_api_sdk.models.change_tracking_response import ChangeTrackingResponse

class TestChangeTrackingResponse(unittest.TestCase):
    """ChangeTrackingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChangeTrackingResponse:
        """Test ChangeTrackingResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChangeTrackingResponse`
        """
        model = ChangeTrackingResponse()
        if include_optional:
            return ChangeTrackingResponse(
                indicator = '',
                type = '',
                tracking = whisper_api_sdk.models.tracking_config.TrackingConfig(
                    enabled = True, 
                    fields = [
                        ''
                        ], 
                    frequency = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_check = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    next_check = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    username = '', 
                    type = '', 
                    value = '', ),
                changes = [
                    whisper_api_sdk.models.change_event.ChangeEvent(
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        field = '', 
                        old_value = whisper_api_sdk.models.old_value.oldValue(), 
                        new_value = whisper_api_sdk.models.old_value.oldValue(), 
                        category = '', 
                        severity = '', )
                    ],
                baseline = whisper_api_sdk.models.old_value.oldValue(),
                baseline_captured_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                total_changes = 56,
                error = '',
                success = True
            )
        else:
            return ChangeTrackingResponse(
        )
        """

    def testChangeTrackingResponse(self):
        """Test ChangeTrackingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
