# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whisper_api_sdk.models.percentile_info import PercentileInfo

class TestPercentileInfo(unittest.TestCase):
    """PercentileInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PercentileInfo:
        """Test PercentileInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PercentileInfo`
        """
        model = PercentileInfo()
        if include_optional:
            return PercentileInfo(
                p25 = 32.1,
                p50 = 44.8,
                p75 = 58.3,
                p90 = 72.1
            )
        else:
            return PercentileInfo(
        )
        """

    def testPercentileInfo(self):
        """Test PercentileInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
