# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whisper_api_sdk.models.dns_info import DnsInfo

class TestDnsInfo(unittest.TestCase):
    """DnsInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DnsInfo:
        """Test DnsInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DnsInfo`
        """
        model = DnsInfo()
        if include_optional:
            return DnsInfo(
                arecords = [
                    ''
                    ],
                a_records = ["8.8.8.8","8.8.4.4"],
                aaaa_records = ["2001:4860:4860::8888"],
                mx_records = [
                    whisper_api_sdk.models.old_value.oldValue()
                    ],
                ns_records = ["ns1.google.com","ns2.google.com"],
                txt_records = [
                    ''
                    ],
                cname_records = [
                    ''
                    ]
            )
        else:
            return DnsInfo(
        )
        """

    def testDnsInfo(self):
        """Test DnsInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
