# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whisper_api_sdk.models.monitor_dashboard_response import MonitorDashboardResponse

class TestMonitorDashboardResponse(unittest.TestCase):
    """MonitorDashboardResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MonitorDashboardResponse:
        """Test MonitorDashboardResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MonitorDashboardResponse`
        """
        model = MonitorDashboardResponse()
        if include_optional:
            return MonitorDashboardResponse(
                total_checks = 10,
                passing_checks = 8,
                failing_checks = 1,
                degraded_checks = 1,
                overall_status = 'passing',
                avg_uptime24_hours = 99.95,
                avg_uptime7_days = 99.87,
                avg_uptime30_days = 99.92,
                avg_response_time = 312,
                checks_by_type = {"api":8,"ssl":1,"dns":1},
                checks_by_status = {"passing":8,"failing":1,"degraded":1},
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return MonitorDashboardResponse(
        )
        """

    def testMonitorDashboardResponse(self):
        """Test MonitorDashboardResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
