# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whisper_api_sdk.models.error_response import ErrorResponse

class TestErrorResponse(unittest.TestCase):
    """ErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorResponse:
        """Test ErrorResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorResponse`
        """
        model = ErrorResponse()
        if include_optional:
            return ErrorResponse(
                status = 400,
                error = 'INVALID_INDICATOR',
                message = 'The provided IP address is not a valid IPv4 or IPv6 address',
                details = {"field":"ip","issue":"Invalid format"},
                timestamp = '2024-12-20T10:15:30.123Z',
                trace_id = '550e8400-e29b-41d4-a716-446655440000',
                path = '/v1/indicators/ip/invalid-ip'
            )
        else:
            return ErrorResponse(
                status = 400,
                error = 'INVALID_INDICATOR',
                message = 'The provided IP address is not a valid IPv4 or IPv6 address',
                timestamp = '2024-12-20T10:15:30.123Z',
        )
        """

    def testErrorResponse(self):
        """Test ErrorResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
