# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whisper_api_sdk.models.links_info import LinksInfo

class TestLinksInfo(unittest.TestCase):
    """LinksInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinksInfo:
        """Test LinksInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinksInfo`
        """
        model = LinksInfo()
        if include_optional:
            return LinksInfo(
                total = 1523,
                top_sources = ["example.com","test.org"],
                top_destinations = ["accounts.google.com","support.google.com"]
            )
        else:
            return LinksInfo(
        )
        """

    def testLinksInfo(self):
        """Test LinksInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
