# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whisper_api_sdk.models.investigate_request import InvestigateRequest

class TestInvestigateRequest(unittest.TestCase):
    """InvestigateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvestigateRequest:
        """Test InvestigateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvestigateRequest`
        """
        model = InvestigateRequest()
        if include_optional:
            return InvestigateRequest(
                indicator = '8.8.8.8',
                indicator_type = 'ip',
                depth = 'comprehensive',
                context = whisper_api_sdk.models.investigate_context.InvestigateContext(
                    hypothesis = '', 
                    related_indicators = [
                        ''
                        ], 
                    time_range = '30d', )
            )
        else:
            return InvestigateRequest(
                indicator = '8.8.8.8',
                indicator_type = 'ip',
        )
        """

    def testInvestigateRequest(self):
        """Test InvestigateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
