# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whisper_api_sdk.models.change_tracking_request import ChangeTrackingRequest

class TestChangeTrackingRequest(unittest.TestCase):
    """ChangeTrackingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChangeTrackingRequest:
        """Test ChangeTrackingRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChangeTrackingRequest`
        """
        model = ChangeTrackingRequest()
        if include_optional:
            return ChangeTrackingRequest(
                fields = ["dns","whois","ssl"],
                frequency = 'daily',
                enabled = True
            )
        else:
            return ChangeTrackingRequest(
        )
        """

    def testChangeTrackingRequest(self):
        """Test ChangeTrackingRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
