# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whisper_api_sdk.api.operations_api import OperationsApi


class TestOperationsApi(unittest.TestCase):
    """OperationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OperationsApi()

    def tearDown(self) -> None:
        pass

    def test_bulk_enrichment(self) -> None:
        """Test case for bulk_enrichment

        Bulk Indicator Enrichment (Asynchronous)
        """
        pass

    def test_create_infrastructure_map(self) -> None:
        """Test case for create_infrastructure_map

        Map Infrastructure Relationships (Asynchronous)
        """
        pass

    def test_create_infrastructure_scan(self) -> None:
        """Test case for create_infrastructure_scan

        Infrastructure Security Scan (Asynchronous)
        """
        pass

    def test_create_monitor_check(self) -> None:
        """Test case for create_monitor_check

        Create Monitoring Check
        """
        pass

    def test_create_monitoring_alert(self) -> None:
        """Test case for create_monitoring_alert

        Configure Monitoring Alerts (Asynchronous)
        """
        pass

    def test_create_screenshot(self) -> None:
        """Test case for create_screenshot

        Capture a Website Screenshot (Asynchronous)
        """
        pass

    def test_delete_monitor_check(self) -> None:
        """Test case for delete_monitor_check

        Delete Monitoring Check
        """
        pass

    def test_get_changes(self) -> None:
        """Test case for get_changes

        Get Detected Changes
        """
        pass

    def test_get_job(self) -> None:
        """Test case for get_job

        Get Asynchronous Job Status and Results
        """
        pass

    def test_get_monitor_check(self) -> None:
        """Test case for get_monitor_check

        Get Monitoring Check
        """
        pass

    def test_get_monitor_dashboard(self) -> None:
        """Test case for get_monitor_dashboard

        Get Monitoring Dashboard
        """
        pass

    def test_get_monitor_results(self) -> None:
        """Test case for get_monitor_results

        Get Check Results
        """
        pass

    def test_get_monitoring_status(self) -> None:
        """Test case for get_monitoring_status

        Get Monitoring Status and Metrics
        """
        pass

    def test_get_screenshot_history(self) -> None:
        """Test case for get_screenshot_history

        Get Screenshot History
        """
        pass

    def test_list_jobs(self) -> None:
        """Test case for list_jobs

        List Recent Jobs
        """
        pass

    def test_list_monitor_checks(self) -> None:
        """Test case for list_monitor_checks

        List Monitoring Checks
        """
        pass

    def test_list_tracked_indicators(self) -> None:
        """Test case for list_tracked_indicators

        List Tracked Indicators
        """
        pass

    def test_schedule_screenshot(self) -> None:
        """Test case for schedule_screenshot

        Schedule Recurring Screenshots (Asynchronous)
        """
        pass

    def test_search_indicators(self) -> None:
        """Test case for search_indicators

        Search Indicators (Asynchronous)
        """
        pass

    def test_similar_domains(self) -> None:
        """Test case for similar_domains

        Find Similar Domains (Asynchronous)
        """
        pass

    def test_start_change_tracking(self) -> None:
        """Test case for start_change_tracking

        Start Change Tracking
        """
        pass

    def test_stop_change_tracking(self) -> None:
        """Test case for stop_change_tracking

        Stop Change Tracking
        """
        pass

    def test_trigger_check(self) -> None:
        """Test case for trigger_check

        Trigger Immediate Check
        """
        pass

    def test_trigger_monitor_check(self) -> None:
        """Test case for trigger_monitor_check

        Trigger Manual Check
        """
        pass

    def test_update_monitor_check(self) -> None:
        """Test case for update_monitor_check

        Update Monitoring Check
        """
        pass


if __name__ == '__main__':
    unittest.main()
