# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whisper_api_sdk.models.monitoring_alert_request import MonitoringAlertRequest

class TestMonitoringAlertRequest(unittest.TestCase):
    """MonitoringAlertRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MonitoringAlertRequest:
        """Test MonitoringAlertRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MonitoringAlertRequest`
        """
        model = MonitoringAlertRequest()
        if include_optional:
            return MonitoringAlertRequest(
                type = 'ssl_expiring',
                threshold_days = 14,
                channels = ["email","slack"],
                email = 'alerts@example.com',
                slack_webhook = 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXX',
                webhook_url = 'https://api.example.com/webhook/alerts',
                pagerduty_key = 'R03XXXXXXXXXXXXXXXXXXXXXX'
            )
        else:
            return MonitoringAlertRequest(
                type = 'ssl_expiring',
        )
        """

    def testMonitoringAlertRequest(self):
        """Test MonitoringAlertRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
