# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whisper_api_sdk.models.attribute_request import AttributeRequest

class TestAttributeRequest(unittest.TestCase):
    """AttributeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AttributeRequest:
        """Test AttributeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AttributeRequest`
        """
        model = AttributeRequest()
        if include_optional:
            return AttributeRequest(
                indicators = [
                    ''
                    ],
                context = whisper_api_sdk.models.attribution_context.AttributionContext(
                    observed_ttps = [
                        ''
                        ], 
                    targeted_sector = '', 
                    target_region = '', 
                    timeframe = '2024-01-01 to 2024-12-31', 
                    malware_families = [
                        ''
                        ], )
            )
        else:
            return AttributeRequest(
                indicators = [
                    ''
                    ],
        )
        """

    def testAttributeRequest(self):
        """Test AttributeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
