# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whisper_api_sdk.models.bulk_options import BulkOptions

class TestBulkOptions(unittest.TestCase):
    """BulkOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkOptions:
        """Test BulkOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkOptions`
        """
        model = BulkOptions()
        if include_optional:
            return BulkOptions(
                parallel_processing = True,
                batch_size = 10,
                timeout_per_indicator = 5000,
                continue_on_error = True,
                include_failed = False
            )
        else:
            return BulkOptions(
        )
        """

    def testBulkOptions(self):
        """Test BulkOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
