# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whisper_api_sdk.models.monitor_list_response import MonitorListResponse

class TestMonitorListResponse(unittest.TestCase):
    """MonitorListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MonitorListResponse:
        """Test MonitorListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MonitorListResponse`
        """
        model = MonitorListResponse()
        if include_optional:
            return MonitorListResponse(
                checks = [
                    whisper_api_sdk.models.monitor_check_response.MonitorCheckResponse(
                        id = 'abc123', 
                        name = 'My Website Health', 
                        url = 'https://example.com/health', 
                        type = 'api', 
                        status = 'passing', 
                        enabled = True, 
                        frequency = 10, 
                        locations = ["us-east-1","eu-west-1"], 
                        muted = False, 
                        method = 'GET', 
                        assertions = whisper_api_sdk.models.monitor_assertions.MonitorAssertions(
                            headers = {
                                'key' : ''
                                }, 
                            status_code = 200, 
                            max_response_time = 3000, 
                            contains_text = '"status":"ok"', 
                            not_contains_text = 'error', 
                            ssl_days_until_expiry = 30, 
                            dns_record_value = '93.184.216.34', 
                            dns_record_type = 'A', ), 
                        last_run_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        uptime24_hours = 99.95, 
                        uptime7_days = 99.87, 
                        uptime30_days = 99.92, 
                        response_time = 245, )
                    ],
                total = 10,
                passing = 8,
                failing = 1,
                degraded = 1,
                pending = 0
            )
        else:
            return MonitorListResponse(
        )
        """

    def testMonitorListResponse(self):
        """Test MonitorListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
