# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AttributionContext(BaseModel):
    """
    Attribution context information
    """ # noqa: E501
    observed_ttps: Optional[List[StrictStr]] = Field(default=None, description="Observed MITRE ATT&CK TTPs", alias="observedTTPs")
    targeted_sector: Optional[StrictStr] = Field(default=None, description="Targeted sector/industry", alias="targetedSector")
    target_region: Optional[StrictStr] = Field(default=None, description="Geographic region of targets", alias="targetRegion")
    timeframe: Optional[StrictStr] = Field(default=None, description="Campaign timeframe")
    malware_families: Optional[List[StrictStr]] = Field(default=None, description="Known malware families observed", alias="malwareFamilies")
    __properties: ClassVar[List[str]] = ["observedTTPs", "targetedSector", "targetRegion", "timeframe", "malwareFamilies"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AttributionContext from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AttributionContext from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "observedTTPs": obj.get("observedTTPs"),
            "targetedSector": obj.get("targetedSector"),
            "targetRegion": obj.get("targetRegion"),
            "timeframe": obj.get("timeframe"),
            "malwareFamilies": obj.get("malwareFamilies")
        })
        return _obj


