# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class HomoglyphConfig(BaseModel):
    """
    Configuration for homoglyph (look-alike character) variations
    """ # noqa: E501
    cyrillic: Optional[StrictBool] = Field(default=True, description="Include Cyrillic character substitutions")
    greek: Optional[StrictBool] = Field(default=True, description="Include Greek character substitutions")
    latin: Optional[StrictBool] = Field(default=True, description="Include Latin character substitutions")
    max_substitutions: Optional[Annotated[int, Field(le=5, strict=True, ge=1)]] = Field(default=2, description="Maximum number of character substitutions per domain")
    __properties: ClassVar[List[str]] = ["cyrillic", "greek", "latin", "max_substitutions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HomoglyphConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HomoglyphConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cyrillic": obj.get("cyrillic") if obj.get("cyrillic") is not None else True,
            "greek": obj.get("greek") if obj.get("greek") is not None else True,
            "latin": obj.get("latin") if obj.get("latin") is not None else True,
            "max_substitutions": obj.get("max_substitutions") if obj.get("max_substitutions") is not None else 2
        })
        return _obj


