# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class MonitorDashboardResponse(BaseModel):
    """
    Monitoring dashboard summary
    """ # noqa: E501
    total_checks: Optional[StrictInt] = Field(default=None, description="Total number of checks", alias="totalChecks")
    passing_checks: Optional[StrictInt] = Field(default=None, description="Number of passing checks", alias="passingChecks")
    failing_checks: Optional[StrictInt] = Field(default=None, description="Number of failing checks", alias="failingChecks")
    degraded_checks: Optional[StrictInt] = Field(default=None, description="Number of degraded checks", alias="degradedChecks")
    overall_status: Optional[StrictStr] = Field(default=None, description="Overall status", alias="overallStatus")
    avg_uptime24_hours: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Average uptime percentage over the last 24 hours", alias="avgUptime24Hours")
    avg_uptime7_days: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Average uptime percentage over the last 7 days", alias="avgUptime7Days")
    avg_uptime30_days: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Average uptime percentage over the last 30 days", alias="avgUptime30Days")
    avg_response_time: Optional[StrictInt] = Field(default=None, description="Average response time across all checks in milliseconds", alias="avgResponseTime")
    checks_by_type: Optional[Dict[str, StrictInt]] = Field(default=None, description="Count of checks by type", alias="checksByType")
    checks_by_status: Optional[Dict[str, StrictInt]] = Field(default=None, description="Count of checks by status", alias="checksByStatus")
    last_updated: Optional[datetime] = Field(default=None, description="When this dashboard data was last updated", alias="lastUpdated")
    __properties: ClassVar[List[str]] = ["totalChecks", "passingChecks", "failingChecks", "degradedChecks", "overallStatus", "avgUptime24Hours", "avgUptime7Days", "avgUptime30Days", "avgResponseTime", "checksByType", "checksByStatus", "lastUpdated"]

    @field_validator('overall_status')
    def overall_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['passing', 'failing', 'degraded']):
            raise ValueError("must be one of enum values ('passing', 'failing', 'degraded')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MonitorDashboardResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MonitorDashboardResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "totalChecks": obj.get("totalChecks"),
            "passingChecks": obj.get("passingChecks"),
            "failingChecks": obj.get("failingChecks"),
            "degradedChecks": obj.get("degradedChecks"),
            "overallStatus": obj.get("overallStatus"),
            "avgUptime24Hours": obj.get("avgUptime24Hours"),
            "avgUptime7Days": obj.get("avgUptime7Days"),
            "avgUptime30Days": obj.get("avgUptime30Days"),
            "avgResponseTime": obj.get("avgResponseTime"),
            "checksByType": obj.get("checksByType"),
            "checksByStatus": obj.get("checksByStatus"),
            "lastUpdated": obj.get("lastUpdated")
        })
        return _obj


