# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from whisper_api_sdk.models.monitor_check_response import MonitorCheckResponse
from typing import Optional, Set
from typing_extensions import Self

class MonitorListResponse(BaseModel):
    """
    List of monitoring checks with summary
    """ # noqa: E501
    checks: Optional[List[MonitorCheckResponse]] = Field(default=None, description="List of monitoring checks")
    total: Optional[StrictInt] = Field(default=None, description="Total number of checks")
    passing: Optional[StrictInt] = Field(default=None, description="Number of passing checks")
    failing: Optional[StrictInt] = Field(default=None, description="Number of failing checks")
    degraded: Optional[StrictInt] = Field(default=None, description="Number of degraded checks")
    pending: Optional[StrictInt] = Field(default=None, description="Number of pending checks (not yet run)")
    __properties: ClassVar[List[str]] = ["checks", "total", "passing", "failing", "degraded", "pending"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MonitorListResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in checks (list)
        _items = []
        if self.checks:
            for _item_checks in self.checks:
                if _item_checks:
                    _items.append(_item_checks.to_dict())
            _dict['checks'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MonitorListResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "checks": [MonitorCheckResponse.from_dict(_item) for _item in obj["checks"]] if obj.get("checks") is not None else None,
            "total": obj.get("total"),
            "passing": obj.get("passing"),
            "failing": obj.get("failing"),
            "degraded": obj.get("degraded"),
            "pending": obj.get("pending")
        })
        return _obj


