# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from whisper_api_sdk.models.current_assessment import CurrentAssessment
from whisper_api_sdk.models.early_warning import EarlyWarning
from whisper_api_sdk.models.model_info import ModelInfo
from whisper_api_sdk.models.pattern_matching import PatternMatching
from whisper_api_sdk.models.predictions import Predictions
from whisper_api_sdk.models.query_info import QueryInfo
from whisper_api_sdk.models.risk_factor import RiskFactor
from whisper_api_sdk.models.similar_case import SimilarCase
from whisper_api_sdk.models.trajectory_info import TrajectoryInfo
from typing import Optional, Set
from typing_extensions import Self

class PredictiveRiskResponse(BaseModel):
    """
    ML-based predictive risk assessment for an indicator
    """ # noqa: E501
    query: Optional[QueryInfo] = None
    current_assessment: Optional[CurrentAssessment] = Field(default=None, alias="currentAssessment")
    predictions: Optional[Predictions] = None
    trajectory: Optional[TrajectoryInfo] = None
    risk_factors: Optional[List[RiskFactor]] = Field(default=None, description="Contributing risk factors", alias="riskFactors")
    pattern_matching: Optional[PatternMatching] = Field(default=None, alias="patternMatching")
    early_warnings: Optional[List[EarlyWarning]] = Field(default=None, description="Early warning signals", alias="earlyWarnings")
    similar_cases: Optional[List[SimilarCase]] = Field(default=None, description="Similar historical cases", alias="similarCases")
    model_info: Optional[ModelInfo] = Field(default=None, alias="modelInfo")
    __properties: ClassVar[List[str]] = ["query", "currentAssessment", "predictions", "trajectory", "riskFactors", "patternMatching", "earlyWarnings", "similarCases", "modelInfo"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PredictiveRiskResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of query
        if self.query:
            _dict['query'] = self.query.to_dict()
        # override the default output from pydantic by calling `to_dict()` of current_assessment
        if self.current_assessment:
            _dict['currentAssessment'] = self.current_assessment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of predictions
        if self.predictions:
            _dict['predictions'] = self.predictions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of trajectory
        if self.trajectory:
            _dict['trajectory'] = self.trajectory.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in risk_factors (list)
        _items = []
        if self.risk_factors:
            for _item_risk_factors in self.risk_factors:
                if _item_risk_factors:
                    _items.append(_item_risk_factors.to_dict())
            _dict['riskFactors'] = _items
        # override the default output from pydantic by calling `to_dict()` of pattern_matching
        if self.pattern_matching:
            _dict['patternMatching'] = self.pattern_matching.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in early_warnings (list)
        _items = []
        if self.early_warnings:
            for _item_early_warnings in self.early_warnings:
                if _item_early_warnings:
                    _items.append(_item_early_warnings.to_dict())
            _dict['earlyWarnings'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in similar_cases (list)
        _items = []
        if self.similar_cases:
            for _item_similar_cases in self.similar_cases:
                if _item_similar_cases:
                    _items.append(_item_similar_cases.to_dict())
            _dict['similarCases'] = _items
        # override the default output from pydantic by calling `to_dict()` of model_info
        if self.model_info:
            _dict['modelInfo'] = self.model_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PredictiveRiskResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "query": QueryInfo.from_dict(obj["query"]) if obj.get("query") is not None else None,
            "currentAssessment": CurrentAssessment.from_dict(obj["currentAssessment"]) if obj.get("currentAssessment") is not None else None,
            "predictions": Predictions.from_dict(obj["predictions"]) if obj.get("predictions") is not None else None,
            "trajectory": TrajectoryInfo.from_dict(obj["trajectory"]) if obj.get("trajectory") is not None else None,
            "riskFactors": [RiskFactor.from_dict(_item) for _item in obj["riskFactors"]] if obj.get("riskFactors") is not None else None,
            "patternMatching": PatternMatching.from_dict(obj["patternMatching"]) if obj.get("patternMatching") is not None else None,
            "earlyWarnings": [EarlyWarning.from_dict(_item) for _item in obj["earlyWarnings"]] if obj.get("earlyWarnings") is not None else None,
            "similarCases": [SimilarCase.from_dict(_item) for _item in obj["similarCases"]] if obj.get("similarCases") is not None else None,
            "modelInfo": ModelInfo.from_dict(obj["modelInfo"]) if obj.get("modelInfo") is not None else None
        })
        return _obj


