# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from whisper_api_sdk.models.blacklist_scores import BlacklistScores
from whisper_api_sdk.models.domain_reputation_scores import DomainReputationScores
from typing import Optional, Set
from typing_extensions import Self

class ReputationInfo(BaseModel):
    """
    Reputation scoring and blacklist information for threat assessment
    """ # noqa: E501
    risk_score: Optional[Union[Annotated[float, Field(le=10, strict=True, ge=0)], Annotated[int, Field(le=10, strict=True, ge=0)]]] = Field(default=None, description="Composite risk score (0-10, higher = riskier)")
    blacklists: Optional[BlacklistScores] = None
    domain_reputation: Optional[DomainReputationScores] = None
    __properties: ClassVar[List[str]] = ["risk_score", "blacklists", "domain_reputation"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReputationInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of blacklists
        if self.blacklists:
            _dict['blacklists'] = self.blacklists.to_dict()
        # override the default output from pydantic by calling `to_dict()` of domain_reputation
        if self.domain_reputation:
            _dict['domain_reputation'] = self.domain_reputation.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReputationInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "risk_score": obj.get("risk_score"),
            "blacklists": BlacklistScores.from_dict(obj["blacklists"]) if obj.get("blacklists") is not None else None,
            "domain_reputation": DomainReputationScores.from_dict(obj["domain_reputation"]) if obj.get("domain_reputation") is not None else None
        })
        return _obj


