# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class ScheduleConfig(BaseModel):
    """
    Configuration for scheduling recurring screenshot captures
    """ # noqa: E501
    cron: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Cron expression for scheduling")
    frequency: Optional[StrictStr] = Field(default=None, description="Frequency of captures")
    timezone: Optional[StrictStr] = Field(default='UTC', description="Timezone for scheduled captures")
    retention_count: Optional[Annotated[int, Field(le=1000, strict=True, ge=1)]] = Field(default=30, description="Maximum number of captures to retain")
    enabled: Optional[StrictBool] = Field(default=True, description="Enable/disable the schedule")
    __properties: ClassVar[List[str]] = ["cron", "frequency", "timezone", "retention_count", "enabled"]

    @field_validator('cron')
    def cron_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"Cron expression", value):
            raise ValueError(r"must validate the regular expression /Cron expression/")
        return value

    @field_validator('frequency')
    def frequency_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['hourly', 'daily', 'weekly', 'monthly']):
            raise ValueError("must be one of enum values ('hourly', 'daily', 'weekly', 'monthly')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScheduleConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScheduleConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cron": obj.get("cron"),
            "frequency": obj.get("frequency"),
            "timezone": obj.get("timezone") if obj.get("timezone") is not None else 'UTC',
            "retention_count": obj.get("retention_count") if obj.get("retention_count") is not None else 30,
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else True
        })
        return _obj


