# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class ScreenshotOptions(BaseModel):
    """
    Configuration options for screenshot capture
    """ # noqa: E501
    width: Optional[Annotated[int, Field(le=7680, strict=True, ge=320)]] = Field(default=1920, description="Viewport width in pixels")
    height: Optional[Annotated[int, Field(le=4320, strict=True, ge=240)]] = Field(default=1080, description="Viewport height in pixels")
    full_page: Optional[StrictBool] = Field(default=False, description="Capture the full page height (scrolling screenshot)")
    wait_time: Optional[Annotated[int, Field(le=30000, strict=True, ge=0)]] = Field(default=2000, description="Wait time in milliseconds before taking screenshot")
    format: Optional[Annotated[str, Field(strict=True)]] = Field(default='png', description="Image format for the screenshot")
    quality: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = Field(default=90, description="Image quality (1-100, only for jpeg/webp)")
    user_agent: Optional[StrictStr] = Field(default=None, description="User agent string to use for the request")
    javascript: Optional[StrictBool] = Field(default=True, description="Enable JavaScript execution")
    block_ads: Optional[StrictBool] = Field(default=False, description="Block ads and trackers")
    accept_cookies: Optional[StrictBool] = Field(default=True, description="Accept cookies consent if prompted")
    __properties: ClassVar[List[str]] = ["width", "height", "full_page", "wait_time", "format", "quality", "user_agent", "javascript", "block_ads", "accept_cookies"]

    @field_validator('format')
    def format_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(png|jpeg|webp)$", value):
            raise ValueError(r"must validate the regular expression /^(png|jpeg|webp)$/")
        return value

    @field_validator('format')
    def format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['png', 'jpeg', 'webp']):
            raise ValueError("must be one of enum values ('png', 'jpeg', 'webp')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScreenshotOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScreenshotOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "width": obj.get("width") if obj.get("width") is not None else 1920,
            "height": obj.get("height") if obj.get("height") is not None else 1080,
            "full_page": obj.get("full_page") if obj.get("full_page") is not None else False,
            "wait_time": obj.get("wait_time") if obj.get("wait_time") is not None else 2000,
            "format": obj.get("format") if obj.get("format") is not None else 'png',
            "quality": obj.get("quality") if obj.get("quality") is not None else 90,
            "user_agent": obj.get("user_agent"),
            "javascript": obj.get("javascript") if obj.get("javascript") is not None else True,
            "block_ads": obj.get("block_ads") if obj.get("block_ads") is not None else False,
            "accept_cookies": obj.get("accept_cookies") if obj.get("accept_cookies") is not None else True
        })
        return _obj


