# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from whisper_api_sdk.models.technique_config import TechniqueConfig
from typing import Optional, Set
from typing_extensions import Self

class SimilarDomainRequest(BaseModel):
    """
    Configuration for generating similar domain variations for brand protection and threat hunting
    """ # noqa: E501
    techniques: Optional[List[StrictStr]] = Field(default=None, description="Types of domain variations to generate")
    limit: Optional[Annotated[int, Field(le=1000, strict=True, ge=1)]] = Field(default=100, description="Maximum number of similar domains to generate")
    check_registration: Optional[StrictBool] = Field(default=False, description="Check if generated domains are registered")
    include_dns: Optional[StrictBool] = Field(default=False, description="Include DNS resolution data for registered domains")
    include_risk_score: Optional[StrictBool] = Field(default=True, description="Calculate risk scores for each variation")
    technique_config: Optional[TechniqueConfig] = None
    __properties: ClassVar[List[str]] = ["techniques", "limit", "check_registration", "include_dns", "include_risk_score", "technique_config"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SimilarDomainRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of technique_config
        if self.technique_config:
            _dict['technique_config'] = self.technique_config.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SimilarDomainRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "techniques": obj.get("techniques"),
            "limit": obj.get("limit") if obj.get("limit") is not None else 100,
            "check_registration": obj.get("check_registration") if obj.get("check_registration") is not None else False,
            "include_dns": obj.get("include_dns") if obj.get("include_dns") is not None else False,
            "include_risk_score": obj.get("include_risk_score") if obj.get("include_risk_score") is not None else True,
            "technique_config": TechniqueConfig.from_dict(obj["technique_config"]) if obj.get("technique_config") is not None else None
        })
        return _obj


