# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class SubdomainInfo(BaseModel):
    """
    Detailed information about a discovered subdomain
    """ # noqa: E501
    subdomain: StrictStr = Field(description="The full subdomain name")
    ip_addresses: Optional[List[StrictStr]] = Field(default=None, description="IP addresses associated with the subdomain")
    first_seen: Optional[datetime] = Field(default=None, description="First time this subdomain was observed")
    last_seen: Optional[datetime] = Field(default=None, description="Last time this subdomain was observed")
    record_type: Optional[StrictStr] = Field(default=None, description="Type of subdomain record")
    status: Optional[StrictStr] = Field(default=None, description="Current status of the subdomain")
    technologies: Optional[List[StrictStr]] = Field(default=None, description="Technology stack detected on this subdomain")
    risk_score: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = Field(default=None, description="Risk score for this subdomain (0-100)")
    __properties: ClassVar[List[str]] = ["subdomain", "ip_addresses", "first_seen", "last_seen", "record_type", "status", "technologies", "risk_score"]

    @field_validator('record_type')
    def record_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['A', 'AAAA', 'CNAME', 'MX', 'TXT', 'NS']):
            raise ValueError("must be one of enum values ('A', 'AAAA', 'CNAME', 'MX', 'TXT', 'NS')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['active', 'inactive', 'parked']):
            raise ValueError("must be one of enum values ('active', 'inactive', 'parked')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubdomainInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubdomainInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "subdomain": obj.get("subdomain"),
            "ip_addresses": obj.get("ip_addresses"),
            "first_seen": obj.get("first_seen"),
            "last_seen": obj.get("last_seen"),
            "record_type": obj.get("record_type"),
            "status": obj.get("status"),
            "technologies": obj.get("technologies"),
            "risk_score": obj.get("risk_score")
        })
        return _obj


