# coding: utf-8

"""
    Whisper Security API

    Enterprise threat intelligence and security operations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TrackingConfig(BaseModel):
    """
    Change tracking configuration for an indicator
    """ # noqa: E501
    enabled: Optional[StrictBool] = Field(default=None, description="Whether tracking is currently enabled")
    fields: Optional[List[StrictStr]] = Field(default=None, description="Fields being tracked for changes")
    frequency: Optional[StrictStr] = Field(default=None, description="Check frequency: hourly, daily, or weekly")
    created_at: Optional[datetime] = Field(default=None, description="When tracking was first started", alias="createdAt")
    last_check: Optional[datetime] = Field(default=None, description="When the last check was performed", alias="lastCheck")
    next_check: Optional[datetime] = Field(default=None, description="When the next check is scheduled", alias="nextCheck")
    username: Optional[StrictStr] = Field(default=None, description="Username of the owner")
    type: Optional[StrictStr] = Field(default=None, description="Indicator type: ip or domain")
    value: Optional[StrictStr] = Field(default=None, description="Indicator value")
    __properties: ClassVar[List[str]] = ["enabled", "fields", "frequency", "createdAt", "lastCheck", "nextCheck", "username", "type", "value"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TrackingConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TrackingConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "enabled": obj.get("enabled"),
            "fields": obj.get("fields"),
            "frequency": obj.get("frequency"),
            "createdAt": obj.get("createdAt"),
            "lastCheck": obj.get("lastCheck"),
            "nextCheck": obj.get("nextCheck"),
            "username": obj.get("username"),
            "type": obj.get("type"),
            "value": obj.get("value")
        })
        return _obj


