# coding: utf-8

"""
    Whisper API Platform

    Whisper provides comprehensive intelligence and monitoring capabilities for domains, IPs, and web infrastructure. Access powerful APIs for WHOIS data, DNS analysis, screenshot capture, network intelligence, and more - all through a unified, authenticated interface.  **Key Features:** • Domain intelligence and subdomain discovery • IP geolocation and network analysis • Real-time and historical WHOIS data • Automated website screenshot capture • Network relationship mapping • BGP routing and security intelligence • Infrastructure monitoring and health checks  **Authentication:** All endpoints require Bearer token authentication. Contact support for API access.

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@whisper.security
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DomainerSimilarityType(str, Enum):
    """
    Type of similarity that was used for the search
    """

    """
    allowed enum values
    """
    CONTAINS = 'CONTAINS'
    PREFIX = 'PREFIX'
    SUFFIX = 'SUFFIX'
    TYPO = 'TYPO'
    SOUNDING = 'SOUNDING'
    UTFVARS = 'UTFVARS'
    TLD_VARIANTS = 'TLD_VARIANTS'
    TYPO_OR_SOUNDING = 'TYPO_OR_SOUNDING'
    LEVENSHTEIN = 'LEVENSHTEIN'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DomainerSimilarityType from a JSON string"""
        return cls(json.loads(json_str))


